# Form implementation generated from reading ui file 'ui_login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_windowUI_login(object):
    def setupUi(self, windowUI_login):
        windowUI_login.setObjectName("windowUI_login")
        windowUI_login.resize(1024, 728)
        windowUI_login.setMinimumSize(QtCore.QSize(1024, 728))
        windowUI_login.setMaximumSize(QtCore.QSize(1024, 728))
        windowUI_login.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.centralwidget = QtWidgets.QWidget(parent=windowUI_login)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 #92FFC0, stop:1 #002661);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QFrame#frame_parent{    \n"
"    margin: 10px;\n"
"    border-radius: 20px;\n"
"    background-color: rgba(225, 228, 221, 120)\n"
"}\n"
"\n"
"QLineEdit{\n"
"    min-height: 45px;\n"
"    border-radius: 20px;\n"
"    background-color: #FFFFFF;\n"
"    padding-left: 20px;\n"
"    color: rgb(140, 140, 140);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(139, 142, 139);\n"
"}\n"
"\n"
"QPushButton#pushButton_login{\n"
"    min-height: 45px;\n"
"    border-radius: 20px;\n"
"    background-color: #005662;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton#pushButton_login:hover{\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QCheckBox{\n"
"    font-size: 14px;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(95, 94, 108);\n"
"}\n"
"\n"
"QPushButton#pushButton_forgot{\n"
"    border: 0px;\n"
"    font-style: italic;\n"
"    font-size: 14px;\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.frame_bottom = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_bottom.setGeometry(QtCore.QRect(0, 60, 1024, 671))
        self.frame_bottom.setObjectName("frame_bottom")
        self.frame_parent = QtWidgets.QFrame(parent=self.frame_bottom)
        self.frame_parent.setGeometry(QtCore.QRect(120, 80, 800, 500))
        self.frame_parent.setStyleSheet("")
        self.frame_parent.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_parent.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_parent.setObjectName("frame_parent")
        self.frame_title = QtWidgets.QFrame(parent=self.frame_parent)
        self.frame_title.setGeometry(QtCore.QRect(20, 30, 761, 121))
        self.frame_title.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(parent=self.frame_title)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(-1)
        self.label_title.setFont(font)
        self.label_title.setAutoFillBackground(False)
        self.label_title.setStyleSheet("color:rgb(255,255,255);\n"
"font-family: \'Segoe UI Light\', \'Segoe UI\', Arial, sans-serif;\n"
"font-size:20px;\n"
"")
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.label_login = QtWidgets.QLabel(parent=self.frame_title)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.label_login.setFont(font)
        self.label_login.setStyleSheet("color:rgb(255,255,255);")
        self.label_login.setObjectName("label_login")
        self.verticalLayout.addWidget(self.label_login)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_parent)
        self.frame_2.setGeometry(QtCore.QRect(20, 150, 761, 331))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit_username = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_username.setGeometry(QtCore.QRect(90, 40, 600, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_password.setGeometry(QtCore.QRect(90, 100, 600, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(90, 240, 601, 51))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_remember = QtWidgets.QCheckBox(parent=self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        self.checkBox_remember.setFont(font)
        self.checkBox_remember.setObjectName("checkBox_remember")
        self.horizontalLayout.addWidget(self.checkBox_remember)
        self.pushButton_forgot = QtWidgets.QPushButton(parent=self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        font.setItalic(True)
        self.pushButton_forgot.setFont(font)
        self.pushButton_forgot.setObjectName("pushButton_forgot")
        self.horizontalLayout.addWidget(self.pushButton_forgot)
        self.pushButton_login = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_login.setGeometry(QtCore.QRect(90, 180, 600, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setObjectName("pushButton_login")
        self.pushButton_login.raise_()
        self.lineEdit_username.raise_()
        self.lineEdit_password.raise_()
        self.frame_3.raise_()
        self.frame_top = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_top.setGeometry(QtCore.QRect(0, 0, 1021, 60))
        self.frame_top.setStyleSheet("QPushButton{\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton#pushButton_minimize{\n"
"    color: lightgreen;\n"
"}\n"
"QPushButton#pushButton_max{\n"
"    color: Yellow;\n"
"}\n"
"QPushButton#pushButton_close{\n"
"    color: red;\n"
"}")
        self.frame_top.setObjectName("frame_top")
        self.frame_top_west = QtWidgets.QHBoxLayout(self.frame_top)
        self.frame_top_west.setContentsMargins(0, 0, 0, 0)
        self.frame_top_west.setObjectName("frame_top_west")
        self.frame_user_2 = QtWidgets.QFrame(parent=self.frame_top)
        self.frame_user_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_user_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_user_2.setObjectName("frame_user_2")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.frame_user_2)
        self.horizontalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_37.setSpacing(0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.lab_user_2 = QtWidgets.QLabel(parent=self.frame_user_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(24)
        self.lab_user_2.setFont(font)
        self.lab_user_2.setStyleSheet("color:rgb(255,255,255);")
        self.lab_user_2.setText("")
        self.lab_user_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lab_user_2.setObjectName("lab_user_2")
        self.horizontalLayout_37.addWidget(self.lab_user_2)
        self.frame_top_west.addWidget(self.frame_user_2)
        self.frame_person_2 = QtWidgets.QFrame(parent=self.frame_top)
        self.frame_person_2.setMinimumSize(QtCore.QSize(55, 55))
        self.frame_person_2.setMaximumSize(QtCore.QSize(55, 55))
        self.frame_person_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_person_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_person_2.setObjectName("frame_person_2")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.frame_person_2)
        self.horizontalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_36.setSpacing(0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.lab_person_2 = QtWidgets.QLabel(parent=self.frame_person_2)
        self.lab_person_2.setMaximumSize(QtCore.QSize(55, 55))
        self.lab_person_2.setText("")
        self.lab_person_2.setScaledContents(False)
        self.lab_person_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lab_person_2.setObjectName("lab_person_2")
        self.horizontalLayout_36.addWidget(self.lab_person_2)
        self.frame_top_west.addWidget(self.frame_person_2)
        self.frame_min_2 = QtWidgets.QFrame(parent=self.frame_top)
        self.frame_min_2.setMinimumSize(QtCore.QSize(55, 55))
        self.frame_min_2.setMaximumSize(QtCore.QSize(55, 55))
        self.frame_min_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_min_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_min_2.setObjectName("frame_min_2")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.frame_min_2)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setSpacing(0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.pushButton_minimize = QtWidgets.QPushButton(parent=self.frame_min_2)
        self.pushButton_minimize.setMaximumSize(QtCore.QSize(55, 55))
        self.pushButton_minimize.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.pushButton_minimize.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_minimize.setFlat(True)
        self.pushButton_minimize.setObjectName("pushButton_minimize")
        self.horizontalLayout_32.addWidget(self.pushButton_minimize)
        self.frame_top_west.addWidget(self.frame_min_2)
        self.frame_max_2 = QtWidgets.QFrame(parent=self.frame_top)
        self.frame_max_2.setMinimumSize(QtCore.QSize(55, 55))
        self.frame_max_2.setMaximumSize(QtCore.QSize(55, 55))
        self.frame_max_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_max_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_max_2.setObjectName("frame_max_2")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frame_max_2)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setSpacing(0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.pushButton_max = QtWidgets.QPushButton(parent=self.frame_max_2)
        self.pushButton_max.setMaximumSize(QtCore.QSize(55, 55))
        self.pushButton_max.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.pushButton_max.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.pushButton_max.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_max.setFlat(True)
        self.pushButton_max.setObjectName("pushButton_max")
        self.horizontalLayout_33.addWidget(self.pushButton_max)
        self.frame_top_west.addWidget(self.frame_max_2)
        self.frame_close_3 = QtWidgets.QFrame(parent=self.frame_top)
        self.frame_close_3.setMinimumSize(QtCore.QSize(55, 55))
        self.frame_close_3.setMaximumSize(QtCore.QSize(55, 55))
        self.frame_close_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_close_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_close_3.setObjectName("frame_close_3")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.frame_close_3)
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_34.setSpacing(0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.pushButton_close = QtWidgets.QPushButton(parent=self.frame_close_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_close.sizePolicy().hasHeightForWidth())
        self.pushButton_close.setSizePolicy(sizePolicy)
        self.pushButton_close.setMaximumSize(QtCore.QSize(55, 55))
        self.pushButton_close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.pushButton_close.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_close.setFlat(True)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_34.addWidget(self.pushButton_close)
        self.frame_top_west.addWidget(self.frame_close_3)
        windowUI_login.setCentralWidget(self.centralwidget)

        self.retranslateUi(windowUI_login)
        QtCore.QMetaObject.connectSlotsByName(windowUI_login)

    def retranslateUi(self, windowUI_login):
        _translate = QtCore.QCoreApplication.translate
        windowUI_login.setWindowTitle(_translate("windowUI_login", "Quản lý sinh viên"))
        self.label_title.setText(_translate("windowUI_login", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">QUẢN LÝ SINH VIÊN</span></p></body></html>"))
        self.label_login.setText(_translate("windowUI_login", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#00557f;\">ĐĂNG NHẬP</span></p></body></html>"))
        self.lineEdit_username.setPlaceholderText(_translate("windowUI_login", "tên đăng nhập"))
        self.lineEdit_password.setPlaceholderText(_translate("windowUI_login", "mật khẩu"))
        self.checkBox_remember.setText(_translate("windowUI_login", "Ghi nhớ mật khẩu"))
        self.pushButton_forgot.setText(_translate("windowUI_login", "Quên mật khẩu?"))
        self.pushButton_login.setText(_translate("windowUI_login", "Đăng nhập"))
        self.pushButton_minimize.setToolTip(_translate("windowUI_login", "Thu nhỏ"))
        self.pushButton_minimize.setText(_translate("windowUI_login", "🗕︎"))
        self.pushButton_max.setToolTip(_translate("windowUI_login", "Phóng to"))
        self.pushButton_max.setText(_translate("windowUI_login", "🗖︎"))
        self.pushButton_close.setToolTip(_translate("windowUI_login", "Đóng"))
        self.pushButton_close.setText(_translate("windowUI_login", "🗙︎"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    windowUI_login = QtWidgets.QMainWindow()
    ui = Ui_windowUI_login()
    ui.setupUi(windowUI_login)
    windowUI_login.show()
    sys.exit(app.exec())
