# Form implementation generated from reading ui file 'ui_main2.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_windowUI_main(object):
    def setupUi(self, windowUI_main):
        windowUI_main.setObjectName("windowUI_main")
        windowUI_main.resize(1366, 768)
        windowUI_main.setMinimumSize(QtCore.QSize(1366, 768))
        windowUI_main.setMaximumSize(QtCore.QSize(1366, 768))
        self.centralwidget = QtWidgets.QWidget(parent=windowUI_main)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 #92FFC0, stop:1 #002661);\n"
"    border-radius: 20px;\n"
"}\n"
"QFrame#frame_bottom_content{\n"
"    background-color: rgba(255, 255, 255, 128);\n"
"}\n"
"QStackedWidget#stackedWidget_content{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QGroupBox{\n"
"    color: white;\n"
"}\n"
"QLineEdit{\n"
"    min-height: 45px;\n"
"    border-radius: 20px;\n"
"    background-color: white;\n"
"    padding-left: 20px;\n"
"    color: white;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(139, 142, 139);\n"
"}\n"
"QPushButton{\n"
"/* Set color to white */\n"
"color: white;\n"
"\n"
"/* Set font family to Bahnschrift */\n"
"font-family: \'Bahnschrift\', sans-serif;\n"
"\n"
"/* Set font size to 15 pixels */\n"
"font-size: 20px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_top.setStyleSheet("")
        self.frame_top.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setSpacing(6)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.frame_top_P = QtWidgets.QFrame(parent=self.frame_top)
        self.frame_top_P.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.frame_top_P.setObjectName("frame_top_P")
        self.frame_top_west = QtWidgets.QHBoxLayout(self.frame_top_P)
        self.frame_top_west.setContentsMargins(0, 0, 0, 0)
        self.frame_top_west.setObjectName("frame_top_west")
        self.frame_user_2 = QtWidgets.QFrame(parent=self.frame_top_P)
        self.frame_user_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_user_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_user_2.setObjectName("frame_user_2")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.frame_user_2)
        self.horizontalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_37.setSpacing(0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.lab_user_2 = QtWidgets.QLabel(parent=self.frame_user_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(24)
        self.lab_user_2.setFont(font)
        self.lab_user_2.setStyleSheet("color:rgb(255,255,255);")
        self.lab_user_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lab_user_2.setObjectName("lab_user_2")
        self.horizontalLayout_37.addWidget(self.lab_user_2)
        self.frame_top_west.addWidget(self.frame_user_2)
        self.frame_person_2 = QtWidgets.QFrame(parent=self.frame_top_P)
        self.frame_person_2.setMinimumSize(QtCore.QSize(55, 55))
        self.frame_person_2.setMaximumSize(QtCore.QSize(55, 55))
        self.frame_person_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_person_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_person_2.setObjectName("frame_person_2")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.frame_person_2)
        self.horizontalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_36.setSpacing(0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.lab_person_2 = QtWidgets.QLabel(parent=self.frame_person_2)
        self.lab_person_2.setMaximumSize(QtCore.QSize(55, 55))
        self.lab_person_2.setText("")
        self.lab_person_2.setPixmap(QtGui.QPixmap(":/icons/1x/peple.png"))
        self.lab_person_2.setScaledContents(False)
        self.lab_person_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lab_person_2.setObjectName("lab_person_2")
        self.horizontalLayout_36.addWidget(self.lab_person_2)
        self.frame_top_west.addWidget(self.frame_person_2)
        self.frame_min_2 = QtWidgets.QFrame(parent=self.frame_top_P)
        self.frame_min_2.setMinimumSize(QtCore.QSize(55, 55))
        self.frame_min_2.setMaximumSize(QtCore.QSize(55, 55))
        self.frame_min_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_min_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_min_2.setObjectName("frame_min_2")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.frame_min_2)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setSpacing(0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.pushButton_minimize = QtWidgets.QPushButton(parent=self.frame_min_2)
        self.pushButton_minimize.setMaximumSize(QtCore.QSize(55, 55))
        self.pushButton_minimize.setStyleSheet("")
        self.pushButton_minimize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/1x/hideAsset 53.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_minimize.setIcon(icon)
        self.pushButton_minimize.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_minimize.setFlat(True)
        self.pushButton_minimize.setObjectName("pushButton_minimize")
        self.horizontalLayout_32.addWidget(self.pushButton_minimize)
        self.frame_top_west.addWidget(self.frame_min_2)
        self.frame_max_2 = QtWidgets.QFrame(parent=self.frame_top_P)
        self.frame_max_2.setMinimumSize(QtCore.QSize(55, 55))
        self.frame_max_2.setMaximumSize(QtCore.QSize(55, 55))
        self.frame_max_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_max_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_max_2.setObjectName("frame_max_2")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frame_max_2)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setSpacing(0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.pushButton_max = QtWidgets.QPushButton(parent=self.frame_max_2)
        self.pushButton_max.setMaximumSize(QtCore.QSize(55, 55))
        self.pushButton_max.setStyleSheet("")
        self.pushButton_max.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/1x/max.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_max.setIcon(icon1)
        self.pushButton_max.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_max.setFlat(True)
        self.pushButton_max.setObjectName("pushButton_max")
        self.horizontalLayout_33.addWidget(self.pushButton_max)
        self.frame_top_west.addWidget(self.frame_max_2)
        self.frame_close_3 = QtWidgets.QFrame(parent=self.frame_top_P)
        self.frame_close_3.setMinimumSize(QtCore.QSize(55, 55))
        self.frame_close_3.setMaximumSize(QtCore.QSize(55, 55))
        self.frame_close_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_close_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_close_3.setObjectName("frame_close_3")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.frame_close_3)
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_34.setSpacing(0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.pushButton_close = QtWidgets.QPushButton(parent=self.frame_close_3)
        self.pushButton_close.setMaximumSize(QtCore.QSize(55, 55))
        self.pushButton_close.setStyleSheet("")
        self.pushButton_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/1x/closeAsset 43.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_close.setIcon(icon2)
        self.pushButton_close.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_close.setFlat(True)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_34.addWidget(self.pushButton_close)
        self.frame_top_west.addWidget(self.frame_close_3)
        self.horizontalLayout_31.addWidget(self.frame_top_P)
        self.verticalLayout.addWidget(self.frame_top)
        self.frame_bottom = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_bottom.setObjectName("frame_bottom")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.frame_bottom)
        self.horizontalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_38.setSpacing(0)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.frame_bottom_menu = QtWidgets.QFrame(parent=self.frame_bottom)
        self.frame_bottom_menu.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_bottom_menu.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_bottom_menu.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"    font-family: \'Segoe UI Light\', \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 18px;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"")
        self.frame_bottom_menu.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_bottom_menu.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_bottom_menu.setObjectName("frame_bottom_menu")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_bottom_menu)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.menu_button_1 = QtWidgets.QFrame(parent=self.frame_bottom_menu)
        self.menu_button_1.setMinimumSize(QtCore.QSize(150, 55))
        self.menu_button_1.setMaximumSize(QtCore.QSize(150, 55))
        self.menu_button_1.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.menu_button_1.setAutoFillBackground(False)
        self.menu_button_1.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.menu_button_1.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.menu_button_1.setObjectName("menu_button_1")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.menu_button_1)
        self.horizontalLayout_39.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_39.setSpacing(0)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.pushButton_home = QtWidgets.QPushButton(parent=self.menu_button_1)
        self.pushButton_home.setMinimumSize(QtCore.QSize(150, 55))
        self.pushButton_home.setMaximumSize(QtCore.QSize(150, 55))
        self.pushButton_home.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/1x/homeAsset 46.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_home.setIcon(icon3)
        self.pushButton_home.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_home.setFlat(True)
        self.pushButton_home.setObjectName("pushButton_home")
        self.horizontalLayout_39.addWidget(self.pushButton_home)
        self.verticalLayout_16.addWidget(self.menu_button_1)
        self.menu_button_2 = QtWidgets.QFrame(parent=self.frame_bottom_menu)
        self.menu_button_2.setMinimumSize(QtCore.QSize(150, 55))
        self.menu_button_2.setMaximumSize(QtCore.QSize(150, 55))
        self.menu_button_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.menu_button_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.menu_button_2.setObjectName("menu_button_2")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.menu_button_2)
        self.horizontalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_40.setSpacing(0)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.pushButton_sinhvien = QtWidgets.QPushButton(parent=self.menu_button_2)
        self.pushButton_sinhvien.setMinimumSize(QtCore.QSize(150, 55))
        self.pushButton_sinhvien.setMaximumSize(QtCore.QSize(150, 55))
        self.pushButton_sinhvien.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/1x/peopleAsset 62.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_sinhvien.setIcon(icon4)
        self.pushButton_sinhvien.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_sinhvien.setFlat(True)
        self.pushButton_sinhvien.setObjectName("pushButton_sinhvien")
        self.horizontalLayout_40.addWidget(self.pushButton_sinhvien)
        self.verticalLayout_16.addWidget(self.menu_button_2)
        self.menu_button_3 = QtWidgets.QFrame(parent=self.frame_bottom_menu)
        self.menu_button_3.setMinimumSize(QtCore.QSize(150, 55))
        self.menu_button_3.setMaximumSize(QtCore.QSize(150, 55))
        self.menu_button_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.menu_button_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.menu_button_3.setObjectName("menu_button_3")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.menu_button_3)
        self.horizontalLayout_41.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_41.setSpacing(0)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.pushButton_diemso = QtWidgets.QPushButton(parent=self.menu_button_3)
        self.pushButton_diemso.setMinimumSize(QtCore.QSize(150, 55))
        self.pushButton_diemso.setMaximumSize(QtCore.QSize(150, 55))
        self.pushButton_diemso.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/1x/bookAsset 57.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_diemso.setIcon(icon5)
        self.pushButton_diemso.setIconSize(QtCore.QSize(22, 12))
        self.pushButton_diemso.setFlat(True)
        self.pushButton_diemso.setObjectName("pushButton_diemso")
        self.horizontalLayout_41.addWidget(self.pushButton_diemso)
        self.verticalLayout_16.addWidget(self.menu_button_3)
        self.menu_button_4 = QtWidgets.QFrame(parent=self.frame_bottom_menu)
        self.menu_button_4.setMinimumSize(QtCore.QSize(150, 55))
        self.menu_button_4.setMaximumSize(QtCore.QSize(150, 55))
        self.menu_button_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.menu_button_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.menu_button_4.setObjectName("menu_button_4")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.menu_button_4)
        self.horizontalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_42.setSpacing(0)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.pushButton_doan = QtWidgets.QPushButton(parent=self.menu_button_4)
        self.pushButton_doan.setMinimumSize(QtCore.QSize(150, 55))
        self.pushButton_doan.setMaximumSize(QtCore.QSize(150, 55))
        self.pushButton_doan.setStyleSheet("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/1x/smileAsset 1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_doan.setIcon(icon6)
        self.pushButton_doan.setIconSize(QtCore.QSize(20, 22))
        self.pushButton_doan.setFlat(True)
        self.pushButton_doan.setObjectName("pushButton_doan")
        self.horizontalLayout_42.addWidget(self.pushButton_doan)
        self.verticalLayout_16.addWidget(self.menu_button_4)
        self.menu_button_5 = QtWidgets.QFrame(parent=self.frame_bottom_menu)
        self.menu_button_5.setMinimumSize(QtCore.QSize(150, 0))
        self.menu_button_5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.menu_button_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.menu_button_5.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.menu_button_5.setObjectName("menu_button_5")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.menu_button_5)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_16.addWidget(self.menu_button_5)
        self.horizontalLayout_38.addWidget(self.frame_bottom_menu)
        self.frame_bottom_content = QtWidgets.QFrame(parent=self.frame_bottom)
        self.frame_bottom_content.setStyleSheet("")
        self.frame_bottom_content.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_bottom_content.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_bottom_content.setObjectName("frame_bottom_content")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_bottom_content)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalFrame = QtWidgets.QFrame(parent=self.frame_bottom_content)
        self.horizontalFrame.setStyleSheet("")
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.stackedWidget_content = QtWidgets.QStackedWidget(parent=self.horizontalFrame)
        self.stackedWidget_content.setStyleSheet("background-color: rgba(5, 50, 100, 50);")
        self.stackedWidget_content.setObjectName("stackedWidget_content")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget_content.addWidget(self.page)
        self.page_1_home = QtWidgets.QWidget()
        self.page_1_home.setStyleSheet("")
        self.page_1_home.setObjectName("page_1_home")
        self.frame_page_1_top = QtWidgets.QFrame(parent=self.page_1_home)
        self.frame_page_1_top.setGeometry(QtCore.QRect(0, 0, 1095, 81))
        self.frame_page_1_top.setAutoFillBackground(False)
        self.frame_page_1_top.setStyleSheet("")
        self.frame_page_1_top.setObjectName("frame_page_1_top")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_page_1_top)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_page_1_title = QtWidgets.QLabel(parent=self.frame_page_1_top)
        self.label_page_1_title.setMinimumSize(QtCore.QSize(0, 55))
        self.label_page_1_title.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_page_1_title.setFont(font)
        self.label_page_1_title.setStyleSheet("background-color: rgba(5, 50, 100, 0);")
        self.label_page_1_title.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_page_1_title.setObjectName("label_page_1_title")
        self.verticalLayout_22.addWidget(self.label_page_1_title)
        self.frame_page_1_bottom = QtWidgets.QFrame(parent=self.page_1_home)
        self.frame_page_1_bottom.setGeometry(QtCore.QRect(0, 90, 1095, 562))
        self.frame_page_1_bottom.setObjectName("frame_page_1_bottom")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_page_1_bottom)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_page_1_thongtin = QtWidgets.QLabel(parent=self.frame_page_1_bottom)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_page_1_thongtin.setFont(font)
        self.label_page_1_thongtin.setStyleSheet("background-color: rgba(5, 50, 100, 0);")
        self.label_page_1_thongtin.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_page_1_thongtin.setWordWrap(True)
        self.label_page_1_thongtin.setObjectName("label_page_1_thongtin")
        self.verticalLayout_23.addWidget(self.label_page_1_thongtin)
        self.stackedWidget_content.addWidget(self.page_1_home)
        self.page_2_sinhvien = QtWidgets.QWidget()
        self.page_2_sinhvien.setStyleSheet("QFrame{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"}\n"
"QGroupBox{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"}\n"
"QTableWidget{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    min-height: 45px;\n"
"    border-radius: 20px;\n"
"    background-color: rgba(255, 255, 255, 0.9);\n"
"    padding-left: 20px;\n"
"    color: blue;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(139, 142, 139);\n"
"}\n"
"QLabel#label_page_2_title{\n"
"    color: #00ffff;\n"
"    font-size: 32px;\n"
"    text-align: center;\n"
"    font-weight: bold;\n"
"}\n"
"QLabel{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color: lightblue;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}")
        self.page_2_sinhvien.setObjectName("page_2_sinhvien")
        self.frame_page_2_sinhvien_main = QtWidgets.QFrame(parent=self.page_2_sinhvien)
        self.frame_page_2_sinhvien_main.setGeometry(QtCore.QRect(0, 0, 1181, 671))
        self.frame_page_2_sinhvien_main.setObjectName("frame_page_2_sinhvien_main")
        self.widget_page_2_sinhvien_left = QtWidgets.QWidget(parent=self.frame_page_2_sinhvien_main)
        self.widget_page_2_sinhvien_left.setGeometry(QtCore.QRect(180, 0, 16777215, 667))
        self.widget_page_2_sinhvien_left.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_page_2_sinhvien_left.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_page_2_sinhvien_left.setObjectName("widget_page_2_sinhvien_left")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_page_2_sinhvien_left)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_page_2_title = QtWidgets.QWidget(parent=self.widget_page_2_sinhvien_left)
        self.widget_page_2_title.setObjectName("widget_page_2_title")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_page_2_title)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_page_2_title = QtWidgets.QLabel(parent=self.widget_page_2_title)
        self.label_page_2_title.setMinimumSize(QtCore.QSize(0, 25))
        self.label_page_2_title.setObjectName("label_page_2_title")
        self.verticalLayout_9.addWidget(self.label_page_2_title)
        self.groupBox_page_2 = QtWidgets.QGroupBox(parent=self.widget_page_2_title)
        self.groupBox_page_2.setMinimumSize(QtCore.QSize(0, 135))
        self.groupBox_page_2.setObjectName("groupBox_page_2")
        self.horizontalFrame_page_2 = QtWidgets.QFrame(parent=self.groupBox_page_2)
        self.horizontalFrame_page_2.setGeometry(QtCore.QRect(50, 5, 741, 131))
        self.horizontalFrame_page_2.setObjectName("horizontalFrame_page_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame_page_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalFrame_page_2_a = QtWidgets.QFrame(parent=self.horizontalFrame_page_2)
        self.verticalFrame_page_2_a.setMinimumSize(QtCore.QSize(130, 0))
        self.verticalFrame_page_2_a.setStyleSheet("\n"
"background-color: rgba(0, 0, 0, 0);\n"
"")
        self.verticalFrame_page_2_a.setObjectName("verticalFrame_page_2_a")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame_page_2_a)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_page_2_search1 = QtWidgets.QLabel(parent=self.verticalFrame_page_2_a)
        self.label_page_2_search1.setMinimumSize(QtCore.QSize(0, 0))
        self.label_page_2_search1.setStyleSheet("")
        self.label_page_2_search1.setObjectName("label_page_2_search1")
        self.verticalLayout_2.addWidget(self.label_page_2_search1)
        self.label_page_2_search2 = QtWidgets.QLabel(parent=self.verticalFrame_page_2_a)
        self.label_page_2_search2.setObjectName("label_page_2_search2")
        self.verticalLayout_2.addWidget(self.label_page_2_search2)
        self.horizontalLayout.addWidget(self.verticalFrame_page_2_a)
        self.verticalFrame_page_2_b = QtWidgets.QFrame(parent=self.horizontalFrame_page_2)
        self.verticalFrame_page_2_b.setObjectName("verticalFrame_page_2_b")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalFrame_page_2_b)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lineEdit_page_2_search1 = QtWidgets.QLineEdit(parent=self.verticalFrame_page_2_b)
        self.lineEdit_page_2_search1.setObjectName("lineEdit_page_2_search1")
        self.verticalLayout_11.addWidget(self.lineEdit_page_2_search1)
        self.lineEdit_page_2_search2 = QtWidgets.QLineEdit(parent=self.verticalFrame_page_2_b)
        self.lineEdit_page_2_search2.setObjectName("lineEdit_page_2_search2")
        self.verticalLayout_11.addWidget(self.lineEdit_page_2_search2)
        self.horizontalLayout.addWidget(self.verticalFrame_page_2_b)
        self.verticalFrame_page_2_c = QtWidgets.QFrame(parent=self.horizontalFrame_page_2)
        self.verticalFrame_page_2_c.setMinimumSize(QtCore.QSize(140, 0))
        self.verticalFrame_page_2_c.setObjectName("verticalFrame_page_2_c")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalFrame_page_2_c)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.pushButton_page_2_search1 = QtWidgets.QPushButton(parent=self.verticalFrame_page_2_c)
        self.pushButton_page_2_search1.setObjectName("pushButton_page_2_search1")
        self.verticalLayout_13.addWidget(self.pushButton_page_2_search1)
        self.pushButton_page_2_search2 = QtWidgets.QPushButton(parent=self.verticalFrame_page_2_c)
        self.pushButton_page_2_search2.setObjectName("pushButton_page_2_search2")
        self.verticalLayout_13.addWidget(self.pushButton_page_2_search2)
        self.horizontalLayout.addWidget(self.verticalFrame_page_2_c)
        self.verticalLayout_9.addWidget(self.groupBox_page_2)
        self.verticalLayout_4.addWidget(self.widget_page_2_title)
        self.widget_page_2_content = QtWidgets.QWidget(parent=self.widget_page_2_sinhvien_left)
        self.widget_page_2_content.setMinimumSize(QtCore.QSize(0, 461))
        self.widget_page_2_content.setMaximumSize(QtCore.QSize(16777215, 461))
        self.widget_page_2_content.setObjectName("widget_page_2_content")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_page_2_content)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableWidget_page2 = QtWidgets.QTableWidget(parent=self.widget_page_2_content)
        self.tableWidget_page2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget_page2.setRowCount(20)
        self.tableWidget_page2.setColumnCount(15)
        self.tableWidget_page2.setObjectName("tableWidget_page2")
        self.verticalLayout_7.addWidget(self.tableWidget_page2)
        self.verticalLayout_4.addWidget(self.widget_page_2_content)
        self.stackedWidget_content.addWidget(self.page_2_sinhvien)
        self.page_3_diemso = QtWidgets.QWidget()
        self.page_3_diemso.setObjectName("page_3_diemso")
        self.frame_page_3_bottom = QtWidgets.QFrame(parent=self.page_3_diemso)
        self.frame_page_3_bottom.setGeometry(QtCore.QRect(0, 90, 1095, 562))
        self.frame_page_3_bottom.setObjectName("frame_page_3_bottom")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_page_3_bottom)
        self.verticalLayout_6.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableWidget_diemso = QtWidgets.QTableWidget(parent=self.frame_page_3_bottom)
        self.tableWidget_diemso.setObjectName("tableWidget_diemso")
        self.tableWidget_diemso.setColumnCount(0)
        self.tableWidget_diemso.setRowCount(0)
        self.verticalLayout_6.addWidget(self.tableWidget_diemso)
        self.frame_page_3_top = QtWidgets.QFrame(parent=self.page_3_diemso)
        self.frame_page_3_top.setGeometry(QtCore.QRect(0, 0, 1095, 81))
        self.frame_page_3_top.setStyleSheet("")
        self.frame_page_3_top.setObjectName("frame_page_3_top")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_page_3_top)
        self.verticalLayout_20.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_20.setSpacing(1)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.widget_page_3_title = QtWidgets.QWidget(parent=self.frame_page_3_top)
        self.widget_page_3_title.setStyleSheet("background-color: rgba(5, 50, 100, 0);")
        self.widget_page_3_title.setObjectName("widget_page_3_title")
        self.layout_page_3_title = QtWidgets.QVBoxLayout(self.widget_page_3_title)
        self.layout_page_3_title.setContentsMargins(1, 1, 1, 1)
        self.layout_page_3_title.setSpacing(6)
        self.layout_page_3_title.setObjectName("layout_page_3_title")
        self.label_page_3_title = QtWidgets.QLabel(parent=self.widget_page_3_title)
        self.label_page_3_title.setObjectName("label_page_3_title")
        self.layout_page_3_title.addWidget(self.label_page_3_title)
        self.verticalLayout_20.addWidget(self.widget_page_3_title)
        self.widget_page_3_buttons = QtWidgets.QWidget(parent=self.frame_page_3_top)
        self.widget_page_3_buttons.setStyleSheet("background-color: rgba(5, 50, 100, 90);")
        self.widget_page_3_buttons.setObjectName("widget_page_3_buttons")
        self.layout_page_3_buttons = QtWidgets.QHBoxLayout(self.widget_page_3_buttons)
        self.layout_page_3_buttons.setContentsMargins(1, 1, 1, 1)
        self.layout_page_3_buttons.setSpacing(6)
        self.layout_page_3_buttons.setObjectName("layout_page_3_buttons")
        self.pushButton_page_3_1view = QtWidgets.QPushButton(parent=self.widget_page_3_buttons)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        self.pushButton_page_3_1view.setFont(font)
        self.pushButton_page_3_1view.setStyleSheet("/* Set color to white */\n"
"color: white;\n"
"\n"
"/* Set font family to Bahnschrift */\n"
"font-family: \'Bahnschrift\', sans-serif;\n"
"\n"
"/* Set font size to 15 pixels */\n"
"font-size: 20px;")
        self.pushButton_page_3_1view.setObjectName("pushButton_page_3_1view")
        self.layout_page_3_buttons.addWidget(self.pushButton_page_3_1view)
        self.pushButton_page_3_2add = QtWidgets.QPushButton(parent=self.widget_page_3_buttons)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        self.pushButton_page_3_2add.setFont(font)
        self.pushButton_page_3_2add.setStyleSheet("/* Set color to white */\n"
"color: white;\n"
"\n"
"/* Set font family to Bahnschrift */\n"
"font-family: \'Bahnschrift\', sans-serif;\n"
"\n"
"/* Set font size to 15 pixels */\n"
"font-size: 20px;")
        self.pushButton_page_3_2add.setObjectName("pushButton_page_3_2add")
        self.layout_page_3_buttons.addWidget(self.pushButton_page_3_2add)
        self.pushButton_page_3_3edit = QtWidgets.QPushButton(parent=self.widget_page_3_buttons)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        self.pushButton_page_3_3edit.setFont(font)
        self.pushButton_page_3_3edit.setStyleSheet("/* Set color to white */\n"
"color: white;\n"
"\n"
"/* Set font family to Bahnschrift */\n"
"font-family: \'Bahnschrift\', sans-serif;\n"
"\n"
"/* Set font size to 15 pixels */\n"
"font-size: 20px;")
        self.pushButton_page_3_3edit.setObjectName("pushButton_page_3_3edit")
        self.layout_page_3_buttons.addWidget(self.pushButton_page_3_3edit)
        self.pushButton_page_3_4delete = QtWidgets.QPushButton(parent=self.widget_page_3_buttons)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(-1)
        self.pushButton_page_3_4delete.setFont(font)
        self.pushButton_page_3_4delete.setStyleSheet("/* Set color to white */\n"
"color: white;\n"
"\n"
"/* Set font family to Bahnschrift */\n"
"font-family: \'Bahnschrift\', sans-serif;\n"
"\n"
"/* Set font size to 15 pixels */\n"
"font-size: 20px;")
        self.pushButton_page_3_4delete.setObjectName("pushButton_page_3_4delete")
        self.layout_page_3_buttons.addWidget(self.pushButton_page_3_4delete)
        self.verticalLayout_20.addWidget(self.widget_page_3_buttons)
        self.stackedWidget_content.addWidget(self.page_3_diemso)
        self.page_4_doan = QtWidgets.QWidget()
        self.page_4_doan.setObjectName("page_4_doan")
        self.frame_page_4_top = QtWidgets.QFrame(parent=self.page_4_doan)
        self.frame_page_4_top.setGeometry(QtCore.QRect(0, 0, 1095, 80))
        self.frame_page_4_top.setObjectName("frame_page_4_top")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_page_4_top)
        self.verticalLayout_21.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_21.setSpacing(1)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.widget_page_4_title = QtWidgets.QWidget(parent=self.frame_page_4_top)
        self.widget_page_4_title.setStyleSheet("background-color: rgba(5, 50, 100, 0);")
        self.widget_page_4_title.setObjectName("widget_page_4_title")
        self.layout_page_4_title = QtWidgets.QVBoxLayout(self.widget_page_4_title)
        self.layout_page_4_title.setContentsMargins(1, 1, 1, 1)
        self.layout_page_4_title.setObjectName("layout_page_4_title")
        self.label_page_4_title = QtWidgets.QLabel(parent=self.widget_page_4_title)
        self.label_page_4_title.setStyleSheet("")
        self.label_page_4_title.setObjectName("label_page_4_title")
        self.layout_page_4_title.addWidget(self.label_page_4_title)
        self.verticalLayout_21.addWidget(self.widget_page_4_title)
        self.widget_page_4_buttons = QtWidgets.QWidget(parent=self.frame_page_4_top)
        self.widget_page_4_buttons.setStyleSheet("background-color: rgba(5, 50, 100, 90);")
        self.widget_page_4_buttons.setObjectName("widget_page_4_buttons")
        self.layout_page_4_buttons = QtWidgets.QHBoxLayout(self.widget_page_4_buttons)
        self.layout_page_4_buttons.setContentsMargins(1, 1, 1, 1)
        self.layout_page_4_buttons.setSpacing(6)
        self.layout_page_4_buttons.setObjectName("layout_page_4_buttons")
        self.pushButton_page_4_1view = QtWidgets.QPushButton(parent=self.widget_page_4_buttons)
        self.pushButton_page_4_1view.setStyleSheet("/* Set color to white */\n"
"color: white;\n"
"\n"
"/* Set font family to Bahnschrift */\n"
"font-family: \'Bahnschrift\', sans-serif;\n"
"\n"
"/* Set font size to 15 pixels */\n"
"font-size: 20px;\n"
"")
        self.pushButton_page_4_1view.setObjectName("pushButton_page_4_1view")
        self.layout_page_4_buttons.addWidget(self.pushButton_page_4_1view)
        self.pushButton_page_4_2add = QtWidgets.QPushButton(parent=self.widget_page_4_buttons)
        self.pushButton_page_4_2add.setStyleSheet("/* Set color to white */\n"
"color: white;\n"
"\n"
"/* Set font family to Bahnschrift */\n"
"font-family: \'Bahnschrift\', sans-serif;\n"
"\n"
"/* Set font size to 15 pixels */\n"
"font-size: 20px;\n"
"")
        self.pushButton_page_4_2add.setObjectName("pushButton_page_4_2add")
        self.layout_page_4_buttons.addWidget(self.pushButton_page_4_2add)
        self.pushButton_page_4_3edit = QtWidgets.QPushButton(parent=self.widget_page_4_buttons)
        self.pushButton_page_4_3edit.setStyleSheet("/* Set color to white */\n"
"color: white;\n"
"\n"
"/* Set font family to Bahnschrift */\n"
"font-family: \'Bahnschrift\', sans-serif;\n"
"\n"
"/* Set font size to 15 pixels */\n"
"font-size: 20px;\n"
"")
        self.pushButton_page_4_3edit.setObjectName("pushButton_page_4_3edit")
        self.layout_page_4_buttons.addWidget(self.pushButton_page_4_3edit)
        self.pushButton_page_4_4delete = QtWidgets.QPushButton(parent=self.widget_page_4_buttons)
        self.pushButton_page_4_4delete.setStyleSheet("/* Set color to white */\n"
"color: white;\n"
"\n"
"/* Set font family to Bahnschrift */\n"
"font-family: \'Bahnschrift\', sans-serif;\n"
"\n"
"/* Set font size to 15 pixels */\n"
"font-size: 20px;\n"
"")
        self.pushButton_page_4_4delete.setObjectName("pushButton_page_4_4delete")
        self.layout_page_4_buttons.addWidget(self.pushButton_page_4_4delete)
        self.verticalLayout_21.addWidget(self.widget_page_4_buttons)
        self.frame_page_4_bottom = QtWidgets.QFrame(parent=self.page_4_doan)
        self.frame_page_4_bottom.setGeometry(QtCore.QRect(0, 90, 1095, 571))
        self.frame_page_4_bottom.setObjectName("frame_page_4_bottom")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_page_4_bottom)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tableWidget_doan = QtWidgets.QTableWidget(parent=self.frame_page_4_bottom)
        self.tableWidget_doan.setObjectName("tableWidget_doan")
        self.tableWidget_doan.setColumnCount(0)
        self.tableWidget_doan.setRowCount(0)
        self.verticalLayout_8.addWidget(self.tableWidget_doan)
        self.stackedWidget_content.addWidget(self.page_4_doan)
        self.horizontalLayout_43.addWidget(self.stackedWidget_content)
        self.verticalLayout_18.addWidget(self.horizontalFrame)
        self.horizontalLayout_38.addWidget(self.frame_bottom_content)
        self.verticalLayout.addWidget(self.frame_bottom)
        windowUI_main.setCentralWidget(self.centralwidget)

        self.retranslateUi(windowUI_main)
        self.stackedWidget_content.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(windowUI_main)

    def retranslateUi(self, windowUI_main):
        _translate = QtCore.QCoreApplication.translate
        windowUI_main.setWindowTitle(_translate("windowUI_main", "MainWindow"))
        self.lab_user_2.setText(_translate("windowUI_main", "Admin"))
        self.pushButton_minimize.setToolTip(_translate("windowUI_main", "Minimize"))
        self.pushButton_max.setToolTip(_translate("windowUI_main", "Maximize"))
        self.pushButton_close.setToolTip(_translate("windowUI_main", "Close"))
        self.pushButton_home.setToolTip(_translate("windowUI_main", "Home"))
        self.pushButton_home.setText(_translate("windowUI_main", "Trang chủ"))
        self.pushButton_sinhvien.setToolTip(_translate("windowUI_main", "Bug"))
        self.pushButton_sinhvien.setText(_translate("windowUI_main", "Sinh viên"))
        self.pushButton_diemso.setToolTip(_translate("windowUI_main", "Cloud"))
        self.pushButton_diemso.setText(_translate("windowUI_main", "Điểm số"))
        self.pushButton_doan.setToolTip(_translate("windowUI_main", "Android"))
        self.pushButton_doan.setText(_translate("windowUI_main", "Môn học"))
        self.label_page_1_title.setText(_translate("windowUI_main", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#00ffff; font-family:\'Segoe UI\',\'Segoe UI\',\'Arial\',\'sans-serif\';\">THÔNG TIN ĐỒ ÁN</span></p></body></html>"))
        self.label_page_1_thongtin.setText(_translate("windowUI_main", "<!DOCTYPE html>\n"
"<html lang=\"vi\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>Quản lý sinh viên</title>\n"
"    <style>\n"
"        body {\n"
"            font-family: Arial, sans-serif;\n"
"            color: #ffffff; \n"
"            background-color: transparent; \n"
"            margin: 0;\n"
"            padding: 20px;\n"
"        }\n"
"        .container {\n"
"            max-width: 800px;\n"
"            margin: 0 auto;\n"
"            padding: 20px;\n"
"        }\n"
"        h1 {\n"
"            color: #ffffff; \n"
"        }\n"
"        .student-list {\n"
"            padding: 0;\n"
"            list-style-position: inside; /* Đặt vị trí số bên trong danh sách */\n"
"        }\n"
"        .student-list li {\n"
"            margin: 10px 0;\n"
"            padding: 10px;\n"
"        }\n"
"        .student-id {\n"
"            font-weight: bold;\n"
"        }\n"
"        .student-name {\n"
"            color: #ffffff;\n"
"        }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <h1>Quản lý sinh viên</h1>\n"
"        <p>Sinh viên thực hiện:</p>\n"
"        <ol class=\"student-list\">\n"
"            <li>\n"
"                <span class=\"student-id\">LT.2023.01 - 23410023</span> - <span class=\"student-name\">Mai Kim Lan</span>\n"
"            </li>\n"
"            <li>\n"
"                <span class=\"student-id\">LT.2023.01 - 23410024</span> - <span class=\"student-name\">Đàm Mỹ Linh</span>\n"
"            </li>\n"
"        </ol>\n"
"    </div>\n"
"</body>\n"
"</html>\n"
""))
        self.label_page_2_title.setText(_translate("windowUI_main", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">QUẢN LÝ SINH VIÊN</span></p></body></html>"))
        self.groupBox_page_2.setTitle(_translate("windowUI_main", "Tìm kiếm"))
        self.label_page_2_search1.setText(_translate("windowUI_main", "Mã số sinh viên"))
        self.label_page_2_search2.setText(_translate("windowUI_main", "Tên sinh viên"))
        self.pushButton_page_2_search1.setText(_translate("windowUI_main", "Tìm kiếm"))
        self.pushButton_page_2_search2.setText(_translate("windowUI_main", "Làm mới"))
        self.label_page_3_title.setText(_translate("windowUI_main", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#00ffff; font-family:\'Segoe UI\',\'Segoe UI\',\'Arial\',\'sans-serif\';\">QUẢN LÝ ĐIỂM</span></p></body></html>"))
        self.pushButton_page_3_1view.setText(_translate("windowUI_main", "Xem danh sách"))
        self.pushButton_page_3_2add.setText(_translate("windowUI_main", "Thêm"))
        self.pushButton_page_3_3edit.setText(_translate("windowUI_main", "Sửa"))
        self.pushButton_page_3_4delete.setText(_translate("windowUI_main", "Xóa"))
        self.label_page_4_title.setText(_translate("windowUI_main", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#00ffff; font-family:\'Segoe UI\',\'Segoe UI\',\'Arial\',\'sans-serif\';\">QUẢN LÝ ĐỒ ÁN</span></p></body></html>"))
        self.pushButton_page_4_1view.setText(_translate("windowUI_main", "Xem danh sách"))
        self.pushButton_page_4_2add.setText(_translate("windowUI_main", "Thêm"))
        self.pushButton_page_4_3edit.setText(_translate("windowUI_main", "Sửa"))
        self.pushButton_page_4_4delete.setText(_translate("windowUI_main", "Xóa"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    windowUI_main = QtWidgets.QMainWindow()
    ui = Ui_windowUI_main()
    ui.setupUi(windowUI_main)
    windowUI_main.show()
    sys.exit(app.exec())
